"use strict";

try{
    console.log('inside try');
   // throw new Error("abc");
}
catch(e){
    console.log(e);
}
finally{
    console.log('inside finally');
}

